"""empty message

Revision ID: 5abcbe7c7d6a
Revises: c3503f797aa1
Create Date: 2020-05-14 21:02:24.266387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abcbe7c7d6a'
down_revision = 'c3503f797aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'interpretation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('interpretation', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
