"""empty message

Revision ID: c3503f797aa1
Revises: 5692a391377a
Create Date: 2020-05-14 21:01:25.758852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3503f797aa1'
down_revision = '5692a391377a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'interpretation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('interpretation', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
