"""adds glossary term class

Revision ID: d7454187d853
Revises: 5abcbe7c7d6a
Create Date: 2020-05-17 17:20:44.943645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7454187d853'
down_revision = '5abcbe7c7d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossaryterms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossaryterms_name'), 'glossaryterms', ['name'], unique=False)
    op.drop_column('recommendations', 'interpretation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('interpretation', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_glossaryterms_name'), table_name='glossaryterms')
    op.drop_table('glossaryterms')
    # ### end Alembic commands ###
