"""empty message

Revision ID: e38d7f6101e8
Revises: d7454187d853
Create Date: 2020-05-18 20:59:41.348860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38d7f6101e8'
down_revision = 'd7454187d853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glossaryterms', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('glossaryterms', 'Notes')
    op.drop_column('recommendations', 'interpretation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('interpretation', sa.TEXT(), nullable=True))
    op.add_column('glossaryterms', sa.Column('Notes', sa.TEXT(), nullable=True))
    op.drop_column('glossaryterms', 'notes')
    # ### end Alembic commands ###
